require("plugins")
require("settings")

require("autocomplete_config")
require("lualine_config")
require("tree-sitter_config")
require("nvim-tree_config")
require("nvim-comment_config")
require("todo_config")
require("telescope_config")
require("sessions_config")
require("rose-pine_config")
require("yabs_config")
